ALTER TABLE users
  ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS daily_profile_views INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_contact_views INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_saved_prospects INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_usage_reset_at TIMESTAMPTZ DEFAULT NOW();
