ALTER TABLE users
  ADD COLUMN IF NOT EXISTS lead_states TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS daily_export_rows INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_export_reset_at TIMESTAMPTZ DEFAULT NOW();
